orders/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [

    url(r'^basket_adding/$', views.basket_adding, name='basket_adding'),
    url(r'^checkout/$', views.checkout, name='checkout'),

]

products/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from products import views

urlpatterns = [
    # url(r'^landing123/', views.landing, name='landing'),
    url(r'^product/(?P<product_id>\w+)/$', views.product, name='product'),
]

test_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^', include('products.urls')),
    url(r'^', include('orders.urls')),
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категория товаров'


class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None)
    short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s, %s" % (self.price, self.name)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='static_dev/products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

products/forms.py
from django import forms
from .models import *


# class SubscriberForm(forms.ModelForm):
#
#     class Meta:
#         model = Subscriber
#         exclude = [""]

products/views.py
from django.shortcuts import render
from products.models import *
from django.views.decorators.csrf import ensure_csrf_cookie
@ensure_csrf_cookie


def product(request, product_id):
    product = Product.objects.get(id=product_id)


    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    print(request.session.session_key)


    return render(request, 'products/product.html', locals())

templates/products/product.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-bottom:70px;;margin-top: 80px;">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item" style="margin-top:30px;">
                        <img src="{{ image_item.image.url }}" class="img-fluid">
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Цена: {{ product.price }}
                    </p>
                </div>
                <div>
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs" role="tablist">
                        <li  class="nav-item">
                            <a class="nav-link active" href="#description" role="tab" data-toggle="tab">
                                Описание
                            </a>
                        </li>

                      </ul>

                      <!-- Tab panes -->
                      <div class="tab-content product-description-tabs">
                        <div role="tabpanel" class="tab-pane active" id="description">
                            {{ product.description }}
                            <p style="text-align:justify; margin-top:10px; margin-bottom:5px;;">Чтобы сделать у нас заказ, достаточно выполнить несколько простых действий. Выбрать нужное количество товара, нажать кнопку «Добавить в корзину», далее нажать на значок корзины в поле меню и заполнить простую форму заказа, после чего мы вам перезвоним.<br>Если вы не хотите ждать можете позвонить прямо сейчас по телефону назвав нам необходимую вам модель. </p>
                            <p style="margin: 0 !important"><i class="fa fa-phone" aria-hidden="true"></i>Тел МТС +38(050)7032779</p>
                            <p style="margin: 0 !important"><i class="fa fa-phone" aria-hidden="true"></i>Тел Лугаком +38(072)1180310</p>
                        </div>

                      </div>
                </div>
                <div>
                    <form id="form_buying_product" class="form-inline" action="{% url 'basket_adding' %}">{% csrf_token %}
                        <script type="text/javascript">
                            // using jQuery
                            var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
                        </script>
                        <div class="form-group">
                             <input type="number" class="form-control" name="number" id="number">
                        </div>


                            <div class="form-group">
                                <a href="{% url 'checkout'  %}">
                                <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                                    data-product_id = "{{ product.id }}"
                                    data-name ="{{ product.name }}"
                                    data-price ="{{ product.price }}"
                                >
                                    Добавить в корзину
                                </button>
                                </a>
                            </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}